### ISSUE TITLE
Can you give me detail for ResourceType.ARRAY and ResourceType.PLURAL?

### ISSUE THREAD

**Issue by ihrthk** [koral--/android-gradle-localization-plugin#17]

**Comment by koral--** [comment]
# Plural 
Look at http://developer.android.com/guide/topics/resources/string-resource.html#Plurals
In CSV/XLS(X) text in square brackets is a quantity. Eg the following CSV part:
```csv
cow[one]  ,cow
cow[other],cows
```
should produce something like this
```xml
<plurals name="cow">
        <item quantity="one">cow</item>
        <item quantity="other">cows</item>
</plurals>
```
Then if you use:
```java
String cowsFound = getResources().getQuantityString(R.plurals.cow, count);
```
`cowsFound` will contain `"cow"` if count is 1 or `"cows"` otherwise if locale is English (or other which distinguishes that quantities).
Only quantities listed in mentioned link are supported and only that which matches grammar rules from locale's language will be used at runtime (eg. `zero` won't work in English even if `count==0`). If you place such redundant quantities in languages which don't use them lint will show a warning. On the other hand if you miss some relevant quantity for given language lint will show an error. If ignore that error (eg. use only `zero` in default locale and locale at runtime is English)`Resources$NotFoundException` will be thrown at runtime.
# Array
http://developer.android.com/guide/topics/resources/string-resource.html#StringArray
Arrays are similar, you don't have a quantity but index:
```csv
planets_array[]  ,Mercury
planets_array[],Venus
```
```xml
<string-array name="planets_array">
        <item>Mercury</item>
        <item>Venus</item>
    </string-array>
```
```java
Resources res = getResources();
String[] planets = res.getStringArray(R.array.planets_array);
```
Note that given array in all translation should be equal-sized.
